import 'package:flutter/material.dart';
import 'package:xterm/xterm.dart';

enum TerminalThemeName {
  dark('Dark'),
  midnight('Midnight'),
  graphite('Graphite'),
  nord('Nord'),
  tokyoNight('Tokyo Night');

  const TerminalThemeName(this.label);
  final String label;
}

class TerminalThemePreset {
  final TerminalThemeName name;
  final Color background;
  final Color foreground;
  final Color accent;
  final TerminalTheme theme;

  const TerminalThemePreset({
    required this.name,
    required this.background,
    required this.foreground,
    required this.accent,
    required this.theme,
  });
}

const List<TerminalThemePreset> terminalThemePresets = [
  TerminalThemePreset(
    name: TerminalThemeName.dark,
    background: Color(0xFF0F1115),
    foreground: Color(0xFFE6EAF2),
    accent: Color(0xFF89B4FA),
    theme: TerminalTheme(
      cursor: Color(0xFFE6EAF2),
      selection: Color(0x445E81F4),
      foreground: Color(0xFFE6EAF2),
      background: Color(0xFF0F1115),
      black: Color(0xFF1E1E2E),
      red: Color(0xFFF38BA8),
      green: Color(0xFFA6E3A1),
      yellow: Color(0xFFF9E2AF),
      blue: Color(0xFF89B4FA),
      magenta: Color(0xFFCBA6F7),
      cyan: Color(0xFF89DCEB),
      white: Color(0xFFBAC2DE),
      brightBlack: Color(0xFF585B70),
      brightRed: Color(0xFFF38BA8),
      brightGreen: Color(0xFFA6E3A1),
      brightYellow: Color(0xFFF9E2AF),
      brightBlue: Color(0xFF89B4FA),
      brightMagenta: Color(0xFFCBA6F7),
      brightCyan: Color(0xFF89DCEB),
      brightWhite: Color(0xFFE6EAF2),
      searchHitBackground: Color(0xFFCBA6F7),
      searchHitBackgroundCurrent: Color(0xFFF9E2AF),
      searchHitForeground: Color(0xFF1E1E2E),
    ),
  ),
  TerminalThemePreset(
    name: TerminalThemeName.midnight,
    background: Color(0xFF060B14),
    foreground: Color(0xFFCBD5E1),
    accent: Color(0xFF60A5FA),
    theme: TerminalTheme(
      cursor: Color(0xFF60A5FA),
      selection: Color(0x4460A5FA),
      foreground: Color(0xFFCBD5E1),
      background: Color(0xFF060B14),
      black: Color(0xFF0D1525),
      red: Color(0xFFF87171),
      green: Color(0xFF34D399),
      yellow: Color(0xFFFCD34D),
      blue: Color(0xFF60A5FA),
      magenta: Color(0xFFA78BFA),
      cyan: Color(0xFF22D3EE),
      white: Color(0xFF94A3B8),
      brightBlack: Color(0xFF1E2D40),
      brightRed: Color(0xFFFCA5A5),
      brightGreen: Color(0xFF6EE7B7),
      brightYellow: Color(0xFFFDE68A),
      brightBlue: Color(0xFF93C5FD),
      brightMagenta: Color(0xFFC4B5FD),
      brightCyan: Color(0xFF67E8F9),
      brightWhite: Color(0xFFCBD5E1),
      searchHitBackground: Color(0xFF60A5FA),
      searchHitBackgroundCurrent: Color(0xFFFCD34D),
      searchHitForeground: Color(0xFF060B14),
    ),
  ),
  TerminalThemePreset(
    name: TerminalThemeName.graphite,
    background: Color(0xFF1E1E1E),
    foreground: Color(0xFFD4D4D4),
    accent: Color(0xFF569CD6),
    theme: TerminalTheme(
      cursor: Color(0xFFD4D4D4),
      selection: Color(0x44569CD6),
      foreground: Color(0xFFD4D4D4),
      background: Color(0xFF1E1E1E),
      black: Color(0xFF2D2D2D),
      red: Color(0xFFF44747),
      green: Color(0xFF6A9955),
      yellow: Color(0xFFD7BA7D),
      blue: Color(0xFF569CD6),
      magenta: Color(0xFFC586C0),
      cyan: Color(0xFF4EC9B0),
      white: Color(0xFFCCCCCC),
      brightBlack: Color(0xFF808080),
      brightRed: Color(0xFFF44747),
      brightGreen: Color(0xFFB5CEA8),
      brightYellow: Color(0xFFD7BA7D),
      brightBlue: Color(0xFF9CDCFE),
      brightMagenta: Color(0xFFC586C0),
      brightCyan: Color(0xFF4EC9B0),
      brightWhite: Color(0xFFE8E8E8),
      searchHitBackground: Color(0xFF569CD6),
      searchHitBackgroundCurrent: Color(0xFFD7BA7D),
      searchHitForeground: Color(0xFF1E1E1E),
    ),
  ),
  TerminalThemePreset(
    name: TerminalThemeName.nord,
    background: Color(0xFF2E3440),
    foreground: Color(0xFFECEFF4),
    accent: Color(0xFF88C0D0),
    theme: TerminalTheme(
      cursor: Color(0xFF88C0D0),
      selection: Color(0x4481A1C1),
      foreground: Color(0xFFECEFF4),
      background: Color(0xFF2E3440),
      black: Color(0xFF3B4252),
      red: Color(0xFFBF616A),
      green: Color(0xFFA3BE8C),
      yellow: Color(0xFFEBCB8B),
      blue: Color(0xFF81A1C1),
      magenta: Color(0xFFB48EAD),
      cyan: Color(0xFF88C0D0),
      white: Color(0xFFE5E9F0),
      brightBlack: Color(0xFF4C566A),
      brightRed: Color(0xFFBF616A),
      brightGreen: Color(0xFFA3BE8C),
      brightYellow: Color(0xFFEBCB8B),
      brightBlue: Color(0xFF81A1C1),
      brightMagenta: Color(0xFFB48EAD),
      brightCyan: Color(0xFF8FBCBB),
      brightWhite: Color(0xFFECEFF4),
      searchHitBackground: Color(0xFF88C0D0),
      searchHitBackgroundCurrent: Color(0xFFEBCB8B),
      searchHitForeground: Color(0xFF2E3440),
    ),
  ),
  TerminalThemePreset(
    name: TerminalThemeName.tokyoNight,
    background: Color(0xFF1A1B26),
    foreground: Color(0xFFA9B1D6),
    accent: Color(0xFF7AA2F7),
    theme: TerminalTheme(
      cursor: Color(0xFF7AA2F7),
      selection: Color(0x447AA2F7),
      foreground: Color(0xFFA9B1D6),
      background: Color(0xFF1A1B26),
      black: Color(0xFF1D202F),
      red: Color(0xFFF7768E),
      green: Color(0xFF9ECE6A),
      yellow: Color(0xFFE0AF68),
      blue: Color(0xFF7AA2F7),
      magenta: Color(0xFFBB9AF7),
      cyan: Color(0xFF7DCFFF),
      white: Color(0xFFA9B1D6),
      brightBlack: Color(0xFF414868),
      brightRed: Color(0xFFF7768E),
      brightGreen: Color(0xFF9ECE6A),
      brightYellow: Color(0xFFE0AF68),
      brightBlue: Color(0xFF7AA2F7),
      brightMagenta: Color(0xFFBB9AF7),
      brightCyan: Color(0xFF7DCFFF),
      brightWhite: Color(0xFFC0CAF5),
      searchHitBackground: Color(0xFF7AA2F7),
      searchHitBackgroundCurrent: Color(0xFFE0AF68),
      searchHitForeground: Color(0xFF1A1B26),
    ),
  ),
];

TerminalThemePreset getTerminalThemePreset(TerminalThemeName name) =>
    terminalThemePresets.firstWhere((t) => t.name == name);
